<?xml version="1.0"?>
<robot name="armczb" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <material name="Black"> <color rgba="0.0 0.0 0.0 1.0"/> </material>
  <material name="Red">   <color rgba="0.8 0.0 0.0 1.0"/> </material>
  <material name="White"> <color rgba="1.0 1.0 1.0 1.0"/> </material>
  <material name="Brown"> <color rgba="0.82 0.7 0.55 1.0"/> </material>
  <material name="Yellow"><color rgba="1.0 1.0 0   1.0"/> </material>
  
  <property name="deg_to_rad" value="0.01745329251994329577"/>
  <property name="M_PI" value="3.14159"/>

  <property name="shoulder_pan_width" value="0.04" />
  <property name="shoulder_pan_len"   value="0.08" />

  <property name="shoulder_pitch_len" value="0.105" />
  <property name="shoulder_pitch_width" value="0.04" />
  <property name="shoulder_pitch_height" value="0.04" />

<!--  
  <property name="elbow_roll_width" value="0.02" />
  <property name="elbow_roll_len" value="0.06" />
-->

  <property name="elbow_pitch_len" value="0.105" />
  <property name="elbow_pitch_width" value="0.04" />
  <property name="elbow_pitch_height" value="0.04" />

  <property name="wrist_roll_width" value="0.02" />
  <property name="wrist_roll_len" value="0.04" />

  <property name="wrist_pitch_len" value="0.06" />
  <property name="wrist_pitch_width" value="0.04" />
  <property name="wrist_pitch_height" value="0.04" />

  <property name="finger_width" value="0.02" />
  <property name="finger_len"   value="0.08" />
  <property name="finger_h"   value="0.02" />
  

  <!-- Left gripper -->
  <property name="left_gripper_len" value="0.08" />
  <property name="left_gripper_width" value="0.01" />
  <property name="left_gripper_height" value="0.01" />


  <!-- Right gripper -->
  <property name="right_gripper_len" value="0.08" />
  <property name="right_gripper_width" value="0.01" />
  <property name="right_gripper_height" value="0.01" />



  <!-- Right gripper -->
  <property name="grasp_frame_len" value="0.02" />
  <property name="grasp_frame_width" value="0.02" />
  <property name="grasp_frame_height" value="0.02" />
  
  <!--
      <xacro:include filename="$(find myrobotpkg)/urdf/whatever.urdf.xacro"/>
  -->
  
  <xacro:macro name="inertial_matrix" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0"
	       izz="1.0" />
    </inertial>
  </xacro:macro>

 
  <!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" /> <!-- rotate PI/2 -->
      <geometry> <box size="0.1 0.1 0.1" /> </geometry>
      <material name="White" />
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" /> <!-- rotate PI/2 -->
      <geometry> <box size="0.1 0.1 0.1" /> </geometry>
    </collision>
    <!-- <xacro:inertial_matrix mass="1"/> -->
      
  </link>
  
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>
  

  <joint name="bottom_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="bottom_link"/>
  </joint>

  <link name="bottom_link">
  
    <visual>
      <origin xyz=" 0 0 -0.04"  rpy="0 0 0"/>
      <geometry> <box size="1 1 0.04" /> </geometry>
      <material name="Brown" />
    </visual>

    <collision>
      <origin xyz=" 0 0 -0.04"  rpy="0 0 0"/>
      <geometry> <box size="1 1 0.04" /> </geometry>
    </collision>

  </link>

  <!-- ////////////////////////////////////  -->
  <!-- /////////   shoulder pan   /////////  -->
  <!-- ////////////////////////////////////  -->
  
  <joint name="shoulder_pan_joint" type="revolute">
    <parent   link="base_link"/>
    <child    link="shoulder_pan_link"/>
    <origin   xyz="0 0 0.05" rpy="0 ${M_PI/2} ${M_PI*0}" />
    <axis     xyz="-1 0 0" />
    <limit    effort="300" velocity="1" lower="-2.61799387799" upper="1.98394848567"/>
    <dynamics damping="50" friction="1"/>
  </joint>


  <link name="shoulder_pan_link" >
    <visual>
      <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <cylinder radius="${shoulder_pan_width}" length="${shoulder_pan_len}"/>
      </geometry>
      <material name="Red" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <cylinder radius="${shoulder_pan_width}" length="${shoulder_pan_len}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>
  </link>
  
  <!-- ////////////////////////////////////  -->
  <!-- /////////   shoulder pitch  ////////  -->
  <!-- ////////////////////////////////////  -->

  <joint name="shoulder_pitch_joint" type="revolute">
    <parent link="shoulder_pan_link"/>
    <child link="shoulder_pitch_link"/>
    <origin xyz="-0.041 0.0021 0.0" rpy="-${M_PI/2} 0 ${M_PI/2}" />
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="1" lower="-1.19962513147" upper="1.89994105047" />
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="shoulder_pitch_link" >
    <visual>
      <origin xyz="-0.002 0 0.05" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <box size="${shoulder_pitch_len} ${shoulder_pitch_width} ${shoulder_pitch_height}" />
      </geometry>
      <material name="White" />
    </visual>

    <collision>
      <origin xyz="-0.002 0 0.05" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <box size="${shoulder_pitch_len} ${shoulder_pitch_width} ${shoulder_pitch_height}" />
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>
  </link>
  
  <!-- ////////////////////////////////////  -->
  <!-- /////////   elbow           ////////  -->
  <!-- ////////////////////////////////////  -->

  <joint name="elbow_pitch_joint" type="revolute">
    <parent   link="shoulder_pitch_link"/>
    <child    link="elbow_pitch_link"/>
    <origin   xyz="-0.002 0 0.1206" rpy="${M_PI} 0 ${M_PI/2}" />
    <axis     xyz="0 1 0" />
    <limit    effort="300" velocity="1" lower="-1.5953400194" upper="1.93281579274" />
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="elbow_pitch_link" >
    <visual>
      <origin xyz="0 0 ${ -1 * elbow_pitch_len /2 }" rpy="0 ${M_PI/2} 0" />
      <geometry>
       <box size="${elbow_pitch_len} ${elbow_pitch_width} ${elbow_pitch_height}" />
      </geometry>
      <material name="Red" />
    </visual>

    <collision>
      <origin xyz="0 0 ${ -1 * elbow_pitch_len /2 }" rpy="0 ${M_PI/2} 0" />
      <geometry>
       <box size="${elbow_pitch_len} ${elbow_pitch_width} ${elbow_pitch_height}" />
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>
  </link>

  <!-- ////////////////////////////////////  -->
  <!-- /////////   wrist tilt      ////////  -->
  <!-- ////////////////////////////////////  -->
  
  <joint name="wrist_pitch_joint" type="revolute">
    <parent   link="elbow_pitch_link"/>
    <child    link="wrist_pitch_link"/>
    <origin   xyz="0.0 0.0 -0.1201" rpy="${M_PI/2} 0 -${M_PI/2}" />
    <axis     xyz="1 0 0" />
    <limit    effort="300" velocity="1" lower="-1.5953400194" upper="1.98394848567" />
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="wrist_pitch_link">
    <visual>
      <origin xyz="0 0 0.04" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <box size="${wrist_pitch_len} ${wrist_pitch_width} ${wrist_pitch_height}" />
      </geometry>
      <material name="White" />
    </visual>

    <collision>
      <origin xyz="0 0 0.04 " rpy="0 ${M_PI/2} 0" />
      <geometry>
        <box size="${wrist_pitch_len} ${wrist_pitch_width} ${wrist_pitch_height}" />
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>
  </link>


  <!-- ////////////////////////////////////  -->
  <!-- /////////   wrist rotation  ////////  -->
  <!-- ////////////////////////////////////  -->


  <joint name="wrist_roll_joint" type="revolute">
    <parent link="wrist_pitch_link"/>
    <child link="wrist_roll_link"/>
    <origin xyz="0.0 -0.03 -.02" rpy="0 ${M_PI/2} 0" />
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="1" lower="-1.2" upper="0.7" />
    <dynamics damping="50" friction="1"/>
  </joint>


  <link name="wrist_roll_link" >
    <visual>
      <origin xyz="-0.04 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <cylinder radius="${wrist_roll_width}" length="${wrist_roll_len}"/>
      </geometry>
      <material name="Black" />
    </visual>

    <collision>
      <origin xyz="-0.04 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <cylinder radius="${wrist_roll_width}" length="${wrist_roll_len}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>
  </link>


  <joint name="pincer_joint" type="revolute">
    <parent link="wrist_roll_link"/>
    <child link="finger_link"/>
    <origin xyz="0.0 -0.00 -.0" rpy="0 0 ${M_PI/2} " />
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="1" lower="1.51" upper="2.6128806087" />
    <dynamics damping="50" friction="1"/>
  </joint>
  

    <link name="finger_link" >
    <visual>
      <origin xyz="0.0 0 0.04" rpy="0 0 ${M_PI/2} " />
      <geometry>
        <box size="${finger_width} ${finger_h} ${finger_len}" />
        <!-- <cylinder radius="${finger_width}" length="${finger_len}"/> -->
      </geometry>
      <material name="Yellow" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
      <geometry>
        <cylinder radius="${finger_width}" length="${finger_len}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>
  </link>


  <joint name="pincer_joint2" type="fixed">
    <parent link="wrist_roll_link"/>
    <child link="finger2_link"/>
    <origin xyz="0.0 -0.00 -.0" rpy="0 0 ${M_PI/2} " />
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="1" lower="1.51" upper="2.6128806087" />
    <dynamics damping="50" friction="1"/>
  </joint>
  

  <link name="finger2_link" >
    <visual>
      <origin xyz="0 -0.05 0.03" rpy="0 0 ${M_PI/2} " />
      <geometry>
        <box size="${finger_len} ${finger_width} ${finger_h} " />
      </geometry>
      <material name="Red" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
      <geometry>
        <cylinder radius="${finger_width}" length="${finger_len}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>
  </link>
  
  
</robot>
